version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    hostname: ${POSTGRES_HOST}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: